package com.patient.patientservice.exception;

import com.fasterxml.jackson.annotation.JsonFormat;
import lombok.*;

import java.time.LocalDateTime;

@Getter
@Setter

public record ErrorMessage(int statusCode, @JsonFormat(pattern = "dd/MM/yyyy HH:mm") LocalDateTime timestamp,
                           String message, String description) {
    // No-arg constructor is not needed
    // Getters and setters are not needed, as they are automatically generated by the record
}
